name: "CI"

on:
  push

concurrency:
  # See https://github.com/TWiStErRob/github-workflows/blob/main/snippets/cancel-pr-ci-on-push.yml
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:

  validate:
    name: "🦺 Validation"
    uses: TWiStErRob/github-workflows/.github/workflows/validate.yml@94f2ec4f96e146200f801fe7e09310c79cb2d2b3 # v2
    permissions:
      contents: read
      security-events: write
      actions: read


  build:
    name: "Build"
    needs:
      - validate
    timeout-minutes: 5

    permissions:
      # actions/checkout
      contents: read

    runs-on: ubuntu-latest
    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Set up JDK 17."
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: "Build without testing"
        shell: bash
        run: >
          ./gradlew --no-daemon --no-build-cache --stacktrace assemble testClasses build -x test -x smokeTest


  test-all:
    name: "Tests"
    needs:
      - validate
    uses: ./.github/workflows/tests-run.yml
    with:
      name: 'All'
      test-task: ':test'
      test-pattern: '*'

    permissions:
      contents: read
      checks: write


  test-smoke:
    name: "Tests"
    needs:
      - validate
    uses: ./.github/workflows/tests-run.yml
    with:
      name: 'Smoke'
      test-task: ':smokeTest'
      test-pattern: '*'

    permissions:
      contents: read
      checks: write
