name: "CI"

on:
  push

concurrency:
  # See https://github.com/TWiStErRob/github-workflows/blob/main/snippets/cancel-pr-ci-on-push.yml
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:

  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Validate Gradle Wrapper JARs."
        uses: gradle/wrapper-validation-action@v1

      - name: "Set up JDK 17."
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: "Build without testing"
        run: ./gradlew --no-daemon --no-build-cache --stacktrace assemble testClasses build -x test -x smokeTest

  test-all:
    name: "Tests"
    uses: ./.github/workflows/tests-run.yml
    with:
      name: 'All'
      test-task: ':test'
      test-pattern: '*'

  test-smoke:
    name: "Tests"
    uses: ./.github/workflows/tests-run.yml
    with:
      name: 'Smoke'
      test-task: ':smokeTest'
      test-pattern: '*'
