name: "Scheduled"

on:
  push:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_6_*_*_*
    - cron: '0 6 * * *'

jobs:

  test-cinema:
    name: "Tests"
    uses: ./.github/workflows/tests-run.yml
    with:
      name: 'cinema.twisterrob.net'
      test-task: ':test'
      test-pattern: 'net.twisterrob.web.twisterrob_net.cinema.*'

    permissions:
      contents: read
      checks: write


  test-regex:
    name: "Tests"
    uses: ./.github/workflows/tests-run.yml
    with:
      name: 'regex.twisterrob.net'
      test-task: ':test'
      test-pattern: 'net.twisterrob.web.twisterrob_net.regex.*'

    permissions:
      contents: read
      checks: write


  test-web:
    name: "Tests"
    uses: ./.github/workflows/tests-run.yml
    with:
      name: 'www.twisterrob.net'
      test-task: ':test'
      test-pattern: 'net.twisterrob.web.twisterrob_net.www.*'

    permissions:
      contents: read
      checks: write


  test-uw:
    name: "Tests"
    uses: ./.github/workflows/tests-run.yml
    with:
      name: 'twisterrob.uw.hu'
      test-task: ':test'
      test-pattern: 'net.twisterrob.web.twisterrob_uw_hu.*'

    permissions:
      contents: read
      checks: write
