name: 'Tests: Smoke'
on:
  push:
  workflow_dispatch:
concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On master, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  # More info: https://stackoverflow.com/a/68422069/253468:
  group: ${{ github.ref == 'refs/heads/master' && format('smoke-master-{0}', github.sha) || format('smoke-{0}', github.ref) }}
  cancel-in-progress: true
jobs:
  smoke-test:
    uses: TWiStErRob/net.twisterrob.healthcheck/.github/workflows/run-tests.yml@${{ github.ref }}
    with:
      name: 'Smoke'
      test-task: ':smokeTest'
      test-pattern: '*'
